### ISSUE TITLE
Please release (react 0.14)

### ISSUE THREAD

**Issue by sheerun** [wangzuo/react-input-color#9]
Hey,

I saw you've bumped react dependency but forgot to release react-input-color.

**Comment by sheerun** [comment]
You've also only published on gh-pages branch

**Comment by steve-taylor** [comment]
Yesterday our build broke because you updated 1.6.0 to React 0.14.0. So I decided to bite the bullet and started updating our entire code base to React 0.14.0. And this morning I got in and tried to `npm install` and it's back to depending on React 0.13.1. All the while, it seems the version number in npm has remained at 1.6.0 instead of being incremented on each change. It's your library, do what you want with it between versions and I won't complain because it's free and therefore I'm not entitled to complain. Nevertheless, if you're going to publish it on NPMJS, *please* have the decency to increment the version number on each published change. Thanks in advance.

**Comment by steve-taylor** [comment]
Also, it seems that the currently NPMJS published version of your library is impossible to install. When my project depends on React 0.13.3, npm complains of unmet peer dependencies on react@^0.14.0 and react-dom@^0.14.0. When I instead depend on React 0.14.0, npm complains of an unmet peer dependency on react@^0.13.1.

**Comment by wangzuo** [comment]
I am still testing for the new release.

@steve-taylor the current npm version works with react 0.13.3. I think you have another component depends on 0.14.0, so they dont work together.

**Comment by steve-taylor** [comment]
Nope.

npm 2, react^0.13.3:
![screen shot 2015-10-20 at 12 30 24 pm](https://cloud.githubusercontent.com/assets/1135589/10595997/6c1d991c-7726-11e5-8031-2f84c9a319ee.png)

npm 2, react^0.14.0:
![screen shot 2015-10-20 at 12 32 24 pm](https://cloud.githubusercontent.com/assets/1135589/10596021/a8cd2242-7726-11e5-9f14-88ed7287e4d8.png)

npm 3, react^0.13.3:
![screen shot 2015-10-20 at 12 41 50 pm](https://cloud.githubusercontent.com/assets/1135589/10596119/f9bfc744-7727-11e5-82c2-b5a309a7c225.png)

npm 3, react^0.14.0:
![screen shot 2015-10-20 at 12 43 21 pm](https://cloud.githubusercontent.com/assets/1135589/10596131/2ec03afa-7728-11e5-8a40-ffbb28c59149.png)

**Comment by wangzuo** [comment]
The npm release already updated.

**Comment by steve-taylor** [comment]
Not sure why you closed this, because the released version still doesn't work.
